const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const { StoreItem } = require('./StoreItem');


const cartItemSchema = new Schema({
    // autogenerated _id property
    storeItem: {type: Schema.Types.ObjectId, ref: 'StoreItem'},
    quantity: Number
})

const CartItem = mongoose.model('CartItem ', cartItemSchema);

module.exports = {
    CartItem : CartItem
}
