const mongoose = require('mongoose');
const Schema = mongoose.Schema;


const storeItemSchema = new Schema({
    // autogenerated _id property
    name: String,
    price: Number
})

const StoreItem = mongoose.model('StoreItem', storeItemSchema);

module.exports = {
    StoreItem : StoreItem
}
